[package]
name = "automates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
serde_json = "1.0.113"
serde = { version = "1.0.196", features = ["derive"] }
